[Rllib] Fix RLlib with Tune (revert #63695) (#64501)
## Description
`linux://rllib:examples/ray_tune/appo_hyperparameter_tune` was failing
with

```
==================== Test output for //rllib:examples/ray_tune/appo_hyperparameter_tune:
Traceback (most recent call last):
  File "rllib/examples/ray_tune/appo_hyperparameter_tune.py", line 155, in <module>
    tuner = tune.Tuner(
            ^^^^^^^^^^^
  File "/rayci/python/ray/tune/tuner.py", line 135, in __init__
    self._local_tuner = TunerInternal(**kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/rayci/python/ray/tune/impl/tuner_internal.py", line 161, in __init__
    self.param_space = param_space
    ^^^^^^^^^^^^^^^^
  File "/rayci/python/ray/tune/impl/tuner_internal.py", line 502, in param_space
    param_space = param_space.to_dict()
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/rayci/python/ray/rllib/algorithms/algorithm_config.py", line 753, in to_dict
    config["train_batch_size"] = self.total_train_batch_size
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rayci/python/ray/rllib/algorithms/algorithm_config.py", line 4321, in total_train_batch_size
    return self.train_batch_size_per_learner * (self.num_learners or 1)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for *: 'Integer' and 'int'
================================================================================
```

https://github.com/ray-project/ray/pull/63695 introduced a property for
`total_train_batch_size` however this causes an issue for RLlib + Ray
Tune.
This PR largely reverts the #63695 and adds a check that a Tune
parameter is usable

Signed-off-by: Mark Towers <mark@anyscale.com>
Co-authored-by: Mark Towers <mark@anyscale.com>